dim = require('../dim.js').dim
x=dim.random.random(50,5)
//x=setGrad()
w1=dim.random.random(5,4)
w1.setGrad()
b1=dim.random.random(50,4)
b1.setGrad()
w2=dim.random.random(4,10)
w2.setGrad()
b2=dim.random.random(50,10)
b2.setGrad()
y=dim.random.randint(9,50,1)
//y.setGrad()
m1=dim.nn.relu(x.dot(w1).add(b1))
m2=dim.nn.relu(m1.dot(w2).add(b2))
g=dim.nn.crossEntropy(m2,y)
optim = dim.optim.Adam([w1,b1,w2,b2],{lr:0.5})
for (let i=0;i<5000;i++){
  g.backward()
  optim.step()
  optim.zeroGrad()
  g.gradFn.setCatch(false)
  if (i%100==0)console.log("epoch=",i,"loss=",g.gradFn.eval().value)
}
y.print()
