dim = require('../dim.js').dim
a=dim.array([[1,2,3],[4,5,6]])
a.setGrad()
b=dim.array([[1,2],[3,4],[5,6]])
b.setGrad()
c=dim.array([[1,2,1],[3,4,1]])
c.setGrad()
d=dim.array([0,1])
m1=a.dot(b)
m2=m1.dot(c)
m3=m2.mul(a).log().cos().sqrt()
m4=dim.nn.crossEntropy(m1,d)
g=m4.sum()
//g.backward()
console.log("==========")
console.log("a.grad:",a.grad.value)
console.log("b.grad:",b.grad.value)
console.log("c.grad:",c.grad.value)
